name = "zai-store"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "./public"

[[kv_namespaces]]
binding = "ZAI_STORE_DB"
id = "c76c5a1caae74678a669e89f86a50fe0"
